# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration


# Expose port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql
